### PR TITLE
Shapeless 2.3.7

### PR DESCRIPTION
**Pull request by joroKr21**
@fthomas I found two issues - using some internals in shapeless that changed and a bug fix making `hconsTagged` redundant

### CODE REVIEW

**Comment by joroKr21** [comment]
The MiMa failure is from a transitive dependency so idk what's up with that. Shapeless doesn't depend on macro compat anymore.

**Comment by fthomas** [comment]
Awesome, thank you @joroKr21! What I originally thought of as MiMa failures are actually comming from the https://github.com/alexarchambault/sbt-compatibility plugin (I think). Maybe adding `compatibilityIgnored += "org.typelevel" %% "macro-compat"` or something similar makes `compatibilityReportDependencyIssues` to not fail.

**Comment by joroKr21** [comment]
@fthomas thanks that did the trick 👍

**Review by regadas — APPROVED** [review]
LGTM

**Review by alexarchambault — APPROVED** [review]
Thanks @joroKr21!

**Comment by marconilanna** [comment]
@alexarchambault Would it be possible to release a v2.0.7 that incorporates this change? At the moment, our project breaks compilation if we bump Shapeless to 2.3.7. We won't be able to upgrade to v2.1.0 because it uses cats-effect 3. Thank you.

**Comment by alexarchambault** [comment]
@marconilanna Just open a PR creating a new case-app-cats-effect-2 module, with the same sources as the current cats module, but without the changes of https://github.com/alexarchambault/case-app/pull/294. I'd be fine publishing two cats modules.

**Comment by marconilanna** [comment]
@alexarchambault Thank you, no longer necessary.

**Pull request merged**
