### PR TITLE
Fix error in example

### PR DESCRIPTION
**Pull request by nightscape**

### CODE REVIEW

**Comment by alexarchambault** [comment]
Thanks! I guess the README should use more assertions (validated by tut) to prevent that.

**Comment by nightscape** [comment]
:+1: on the assertions :)

**Comment by nightscape** [comment]
Btw, will there be a 1.0.0-M1 at some point soon? I'd like to switch over from because it gives a lot of warnings, but I'm wary of using SNAPSHOT dependencies...

**Comment by alexarchambault** [comment]
@nightscape The only thing hindering a milestone is that it now depends on shapeless 2.3.0, available only as snapshots for now. I've been trying to backport some of its features to shapeless 2.2, to be able to make releases, but it's still in the making...

**Comment by nightscape** [comment]
I see, it's a transitive problem :)
Thanks for the update!

**Pull request merged**
