### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by larsrh**
* updated shapeless to 2.3.x
* introduced macro-compat to avoid source code redundancy
* cross-compilation against Scala 2.12.0-M5 (RC1 is out, but shapeless doesn't build with RC1, so M5 is the next best thing)

### CODE REVIEW

**Comment by larsrh** [comment]
2.10 test failure is spurious:

```
		[FAILED     ] org.scala-lang#scala-reflect;2.10.6!scala-reflect.jar: Connection reset (728ms)
```

**Comment by alexarchambault** [comment]
@larsrh The [`1.1.x` branch](https://github.com/alexarchambault/case-app/tree/1.1.x), which is supposed to become the next master, already switched to shapeless 2.3 😬 

I think I'll release case-app 1.0 (for shapeless 2.2) and 1.1.0 (for shapeless 2.3) very soon, then switch the master branch.

I can rebase your PR against 1.1.x if you want (and push it straightaway).

**Comment by larsrh** [comment]
Sorry, I completely missed that.

Yes, rebasing would be great, but I don't need a release straight away. I'll take a stab today.

**Comment by larsrh** [comment]
Well, that rebase wasn't as painful as I'd expected. Anyway, here you go :smile:

**Comment by alexarchambault** [comment]
Merging, thanks! The `1.1.x` branch should become master right after that.

**Comment by larsrh** [comment]
:sparkles:

**Pull request merged**
