### PR TITLE
Return all errors from parsing, not just the first.

### LINKED ISSUE #70: Only one missing option is reported at a time
Using caseapp 1.2.0, if you have:
```scala
import caseapp._

case class ExampleOptions(
  foo: String,
  bar: Int
)

object Example extends CaseApp[ExampleOptions] {
  def run(options: ExampleOptions, arg: RemainingArgs): Unit = {
    println(options)
    println(arg)
  }
}
```
If you run without arguments, you see:
```bash
$ sbt -error run
[error] Required option --foo not specified
```
Which is correct, but it'd be awesome if both `--foo` and `--bar` were reported missing.

### PR DESCRIPTION
**Pull request by danxmoran**
Fixes #70.

Let me know if you'd rather I revert adding all the `override` keywords. I like having them for the extra compiler checks, but I see it's not super common in the project.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Thanks!

About handling multiple errors, wouldn't it be possible to do something like:
- adding an extra `abstract class SimpleError extends Error`, and have all the current `Error` implems extend it,
- add a `case class Several(head: SimpleError, tail: List[SimpleError]) extends Error`,
- and use the latter if there are several errors.

That way, just `Error` could be kept in most return types, rather than replacing it with `Seq[Error]` (and that also allows to ensure that at least one error is returned, which just `Seq[Error]` doesn't allow).

(I can push an extra commit in this branch doing just that, if you'd like.)

About the `override`s, I usually avoid them when they're not mandatory, but it's no big deal admittedly…

**Comment by danxmoran** [comment]
Should be doable, I'll try it out later tonight!

**Comment by danxmoran** [comment]
@alexarchambault comments addressed! Much less invasive of a change now.

**Comment by alexarchambault** [comment]
Merging, thanks!

**Pull request merged**
