### PR TITLE
Upgrade cats-effect

### PR DESCRIPTION
**Pull request by joan38**
Supersedes https://github.com/alexarchambault/case-app/pull/287

### CODE REVIEW

**Comment by joan38** [comment]
Ok this is not binary compatible and I don't think we can make it compatible. What should we do? @alexarchambault

**Comment by joan38** [comment]
Any news? Tagging @alexarchambault but not sure if there is another maintainer here.

**Review by alexarchambault — APPROVED** [review]
Thanks! I'm about to cut `2.1.0`, so binary compatibility isn't an issue any more.

**Comment by joan38** [comment]
Speaking about binary compat. I noticed an issue with the latest circe: For some reason when I have the latest circe and case-app, It doesn't work. I have no idea where this is coming from.

**Comment by joan38** [comment]
Actually never mind it's a issue related to when I try to use case-app with Scala 3.0.0

**Pull request merged**
