### PR TITLE
[WIP] #39

### PR DESCRIPTION
**Pull request by tkroman**
This addressed each bullet from the #39 list, but the format is not set in stone. I'd like to hear some feedback on this. E.g.:

1. Lists are rendered as `T*` (int*, long* etc.). I choose to render `Option` as `T?` - is it clear enough?

2. 'required-ness' of parameters is decided solely based on `T =:= Option[_]` - is it OK? Should we consider `List[_]` params optional, too? 

3. Was the `required` flag intended for those types that don't have the `Default` instance associated with them? If that is the case, consider previous question answered.

4. Also, rendering: 

`foo <float> [required] [default: 41.9]`

What would you change here?

### CODE REVIEW

**Comment by tkroman** [comment]
Update: I took a liberty to try and come up with something different that originally proposed.

'Required" is now being rendered _only_ if there's not default argument (vs. non-optional types originally). I think this makes more sense since there's no point in marking an int as required when it will be actually set to 0. WDYT?

Also, added more detailed default value rendering.

**Comment by alexarchambault** [comment]
Looks good overall, thanks! I'll review in detail and answer your questions soon. About the format, something like `--foo <float>    [required, default: 41.9]` would be fine I guess (more space between the arg and the comment, merging the comments if that's not too much a hassle to implement).

Also, it may be possible to add the `ArgHint` methods to `ArgParser`, to avoid creating another type class - it seems both `ArgHint` and `ArgParser` instances are looked for at the same time (I'm now thinking I should have done something along those lines for `Default`).

**Comment by tkroman** [comment]
@alexarchambault ok, will do both merged hints and unification w/ `ArgParser`, so review can wait.

**Comment by tkroman** [comment]
1. Removed the `ArgHint` typeclass.
2. Changed the output, but the question about co-existing 'default' and 'required' is still of interest - is an argument really required if there's a default value for the type? In the current implementation I chose the exclusive policy, but the final decision is up to you.

**Comment by alexarchambault** [comment]
That looks fine!

About the list case, I think it would be better if the message looked like
```
 --list  <int>  [multiple values allowed]
```
with an empty default value, and like
```
 --list  <int>  [multiple values allowed, default: 1,2]
```
with a non empty default value, or like
```
 --list  <int1>,<int2>
 --list  <int1>,<int2>  [default: 1,2]
```
(like scopt does). WDYT?

Also, I might cherry-pick and merge earlier parts of this that I would need right now, I'll take care of a possible rebase if necessary.

**Comment by tkroman** [comment]
I'm leaning towards the `<type*>` (or `<type...>`), since it is 
a) more in line what other tools do (compare to this excerpt from `java -help`): 

`    -ea[:<packagename>...|:<classname>]` 

b) represents the type of the argument fully and in one place instead of being divided between the arg type and hint. And since users don't lose the ability to give hints, we still can do this (from `curl --help`):

`     --dns-servers   DNS server addrs to use: 1.1.1.1;2.2.2.2`, which in our case _could_ be (supposing we define a custom `ip-string` arg parser:

`-- dns-servers <ip-string*> <default: []>`.

Actually, what's more important to me is that since there's a `Default[List]` defined, there's no way to make a non-empty list requirement. Do you think we should provide some `NEArgList` which would not have a `Default` instance? It's type would be `<elem-type+>` (in line with `*`/`+` in regexes) and it could be nice to have static guarantees without relying on some defaults or client behavior.

**Comment by alexarchambault** [comment]
@tkroman Was it mergeable? Parts of this were already merged via other PRs, right? (I think I cherry-picked those.)

**Comment by tkroman** [comment]
There was a lot of conflicts (~10 files), I didn't look close, but got the idea that it's no longer relevant. The branch is still there, you can see for yourself if there is anything worthy to pick up: https://github.com/alexarchambault/case-app/compare/master...tkroman:%2339-wip

**Pull request closed without merging**
