### PR TITLE
Update sbt to 1.5.2

### PR DESCRIPTION
**Pull request by regadas**

### CODE REVIEW

**Comment by regadas** [comment]
Doh 🤦 didn't realize there was already a PR for this

**Comment by regadas** [comment]
@alexarchambault do you know if there are known issues with the sbt-launcher?

**Comment by alexarchambault** [comment]
@regadas I think I need to change things in [coursier/sbt-launcher](https://github.com/coursier/sbt-launcher) for sbt 1.5.x, and / or allow `cs install` to install the vanilla sbt distribution.

**Comment by alexarchambault** [comment]
Closing, https://github.com/alexarchambault/case-app/pull/352 updated the CI setup, so that it relies on vanilla sbt launchers, and bumped the sbt version.

**Comment by alexarchambault** [comment]
Actually, I took bits of this PR in https://github.com/alexarchambault/case-app/pull/353.

**Pull request closed without merging**
