### PR TITLE
fix broken README link

### PR DESCRIPTION
**Pull request by ryan-williams**

### CODE REVIEW

**Comment by alexarchambault** [comment]
Ok, only seeing this now :/

I pushed an extra commit to report these changes to `doc/readme/README.md`, out of which the README at the root is generated (via a `sbt tut`). Feel free to squash it with your commit.

**Comment by ryan-williams** [comment]
wow, didn't notice the tut setup, cool

re: sequashing, I'm happy to have you merge as-is, unless your preference is to squash / avoid merge commits?

**Comment by alexarchambault** [comment]
Ok, I'll merge as-is.

**Comment by alexarchambault** [comment]
Thanks!

**Pull request merged**
